name: dream11_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  flutter_native_splash: ^2.4.4
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^11.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
